version: '2'

vars:
  TERRAFORM_VERSION: 0.12.0
  PROVIDER_VERSION:  2.12.0
  DIRECTORIES:
    sh: find . -type f -name '*.tf' -not -path "**/.terraform/*" -exec dirname {} \; | sort -u
  FILES:
    sh: find . -type f -name '*.tf' -not -path "**/.terraform/*"


tasks:
  directories:
    desc: List terraform directories.
    silent: true
    cmds:
    - echo "{{.DIRECTORIES}}"

  files:
    desc: List all terraform files.
    silent: true
    cmds:
    - echo "{{.FILES}}"

  fmt:
    desc: Check formatting of all terraform files.
    silent: true
    cmds:
    - task: command
      vars:
        COMMAND: terraform fmt
        ARGS: -check=true -write=false -list=false -recursive=false
        PIPE:

  validate:
    desc: Validate all terraform directories.
    silent: true
    cmds:
    - task: command
      vars:
        COMMAND: terraform init
        ARGS: -backend=false -input=false -get=true -get-plugins=true -no-color
        PIPE: '&> /dev/null'
    - task: command
      vars:
        COMMAND: terraform validate
        ARGS: 
        PIPE:
    
  tests:
    desc: Run all tests.
    silent: true
    cmds:
    - task: fmt
    - task: validate

  bump-versions:
    desc: Bump the terraform and aws provider versions.
    silent: true
    cmds:
    - |
      for f in $(echo "{{.FILES}}"); do 
        sed -i '' -E "s/^([ ]*version[ ]*=[ ]*)\"([0-9]+\\.[0-9]+\\.[0-9]+)\"/\\1\"{{.PROVIDER_VERSION}}\"/g" $f
        sed -i '' -E "s/^([ ]*required_version[ ]*=[ ]*)\"([0-9]+\\.[0-9]+\\.[0-9]+)\"/\\1\"{{.TERRAFORM_VERSION}}\"/g" $f
      done

  command:
    desc: Run a command on the directories. 
    silent: true
    cmds:
    - |
      BOLD=$(tput bold)
      NORM=$(tput sgr0)

      echo "${BOLD} {{.COMMAND}}:${NORM}"
      for d in $(echo "{{.DIRECTORIES}}"); do 
        if ! {{.COMMAND}} {{.ARGS}} $d {{.PIPE}}; then
          echo "  ✗ $d"
        else
          echo "  √ $d"
        fi
      done
